### ISSUE TITLE
Panic on callEdge dynamic function call

### ISSUE THREAD

**Issue by Riuchando** [TrueFurby/go-callvis#25] opened 2018-04-26 12:45 UTC
```
Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/debug/stack.go:16 +0x22
github.com/TrueFurby/go-callvis/vendor/golang.org/x/tools/go/pointer.Analyze.func1(0xc44341fa00)
	/Users/*********/code/src/github.com/TrueFurby/go-callvis/vendor/golang.org/x/tools/go/pointer/analysis.go:227 +0x124
panic(0x12aa0a0, 0xc44db24cc0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/panic.go:491 +0x283
github.com/TrueFurby/go-callvis/vendor/golang.org/x/tools/go/pointer.(*analysis).callEdge(0xc4296461c0, 0xc4258ad080, 0xc43bc346c0, 0x13eef)
	/Users/*********/code/src/github.com/TrueFurby/go-callvis/vendor/golang.org/x/tools/go/pointer/analysis.go:368 +0x937
github.com/TrueFurby/go-callvis/vendor/golang.org/x/tools/go/pointer.Analyze(0xc43386d720, 0x0, 0x1490440, 0xc44db24e40)
	/Users/*********/code/src/github.com/TrueFurby/go-callvis/vendor/golang.org/x/tools/go/pointer/analysis.go:354 +0x8b8
main.run(0x14ae8e0, 0x1316ee6, 0x4, 0xc44341fea8, 0x14cd4e8, 0x0, 0x0, 0x14cd4e8, 0x0, 0x0, ...)
	/Users/*********/code/src/github.com/TrueFurby/go-callvis/main.go:159 +0x7ba
main.main()
	/Users/*********/code/src/github.com/TrueFurby/go-callvis/main.go:77 +0x7ee
go-callvis: internal error in pointer analysis: callEdge dynamic function call -> n81647: not a function object (please report this bug)
```

**Comment by TrueFurby** [comment] 2018-04-26 17:49
You report doesn't really give me much information about what command you executed.

However this seems to be duplicate of issue https://github.com/TrueFurby/go-callvis/issues/24

**Comment by Riuchando** [comment] 2018-04-27 20:00
I ran `go-callvis .` in the folder where my main function was located, I thought it might be a duplicate of the other issue but the internal error message was different

**Comment by TrueFurby** [comment] 2018-04-30 14:25
Both are occurring at `golang.org/x/tools/go/pointer/analysis.go:227` though.

**Comment by Riuchando** [comment] 2018-04-30 14:28
okay, thanks, I'll keep an eye on the original bug.

**Closed** 2018-07-21 21:05 UTC
Labels: duplicate
