### ISSUE TITLE
internal error in pointer analysis: callEdge dynamic function call -> n253458: not a function object

### ISSUE THREAD

**Issue by wencan** [TrueFurby/go-callvis#59] opened 2020-01-19 03:29 UTC
```
Internal panic in pointer analysis:
goroutine 1 [running]:
runtime/debug.Stack(0x24, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
golang.org/x/tools/go/pointer.Analyze.func1(0xc011f81d90)
        /Users/klook/go/src/golang.org/x/tools/go/pointer/analysis.go:227 +0x157
panic(0x14e0dc0, 0xc03c2d3360)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
golang.org/x/tools/go/pointer.(*analysis).callEdge(0xc04f1f88c0, 0xc0531dad80, 0xc00bb8fb00, 0x3de12)
        /Users/klook/go/src/golang.org/x/tools/go/pointer/analysis.go:368 +0x78c
golang.org/x/tools/go/pointer.Analyze(0xc04f2c55e0, 0x0, 0x1658140, 0xc03c2d3380)
        /Users/klook/go/src/golang.org/x/tools/go/pointer/analysis.go:354 +0x6e1
main.doAnalysis(0x0, 0x0, 0xc000022200, 0xc0000b8010, 0x1, 0x1, 0xc000030660, 0xc000024540)
        /Users/klook/go/src/github.com/TrueFurby/go-callvis/analysis.go:49 +0x2ec
main.main()
        /Users/klook/go/src/github.com/TrueFurby/go-callvis/main.go:104 +0x158
2020/01/19 11:28:46 internal error in pointer analysis: callEdge dynamic function call -> n253458: not a function object (please report this bug)
```

**Comment by TrueFurby** [comment] 2020-02-22 10:09
Duplicate of #24

**Closed by TrueFurby** 2020-02-22 10:09 UTC
Labels: bug, duplicate
