### ISSUE TITLE
Call graph of server start with run

### ISSUE THREAD

**Issue by gitbub1992** [TrueFurby/go-callvis#38] opened 2018-11-22 02:24 UTC
Hi, I want to use go-callvis to get the call graph of pd server which starts with function Run(). 
Command like this:
`go-callvis -focus=""  -limit github.com/pingcap/pd/server  -ignore github.com/pingcap/pd/vendor  | dot -Tpng -o pd_server.png`

Nothing I got but the usage, so what is the problem?

**Comment by TrueFurby** [comment] 2018-12-15 18:07
This issue is duplicate of: https://github.com/TrueFurby/go-callvis/issues/36 closing it.
Related PR that will fix this: https://github.com/TrueFurby/go-callvis/pull/39

**Closed by TrueFurby** 2018-12-15 18:07 UTC
